name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.75
          components: clippy rustfmt

      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            pkg-config \
            libdbus-1-dev

      - name: Check code formatting
        run: cargo fmt -- --check

      - name: Build documentation
        run: cargo doc --no-deps --quiet

      - name: Run tests
        run: cargo test --quiet

      - name: Code analysis
        run: cargo clippy --quiet

  cross-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - i686-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: cargo-bins/cargo-binstall@v1
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.75

      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            podman \
            qemu-user-static && \
          cargo binstall --no-confirm cross

      - name: Build for ${{ matrix.target }}
        run: CROSS_CONTAINER_ENGINE=podman cross build --target ${{ matrix.target }} --examples --bins
